### ISSUE TITLE
`bin` present in .gitignore and shouldn't be in Dockerfile

### ISSUE THREAD

**Issue by poopsicles** [dreth/Altserver-docker#1]
pretty much the title, removing it from Dockerfile allows the image to be built correctly

**Comment by dreth** [comment]
Oh true, since it's already mapped in the docker run command and in the docker compose yaml it's not necessary to have it in the Dockerfile, thanks, good catch!

**Comment by dreth** [comment]
okay done, I'll add a small gh actions pipeline today to build it so I can catch issues like this, thank you again!
