### ISSUE TITLE
Lockdown error -8:Possible outdated libraries?

### ISSUE THREAD

**Issue by darderik** [dreth/Altserver-docker#5]
Hello, i was trying to setup altserver using this docker after i gave up adapting hkfuertes/altserverd. I noticed that libimobiledevice libraries do not get compiled from source so I was wondering if there was any kind of limit on the iOS version of the device. I'm trying to authorize the usbmuxd instance by connecting the device but nothing is happening. 
[pastebin.com/raw/bN7x1y72](https://pastebin.com/raw/bN7x1y72)

thank you for setting up this repository, 
greetings

**Comment by darderik** [comment]
Oook nevermind. It seems I required to force sudo on usbmuxd and netmuxd... this makes zero sense as the whole docker is running as root, but who am i to judge the logic behind this


> `[program:netmuxd]
command=sudo /altserver/bin/netmuxd --disable-unix --host 127.0.0.1
autostart=true
autorestart=true
stderr_logfile=/altserver/logs/netmuxd.err.log
stdout_logfile=/altserver/logs/netmuxd.out.log
priority=30`

> `[program:usbmuxd]
command=sudo usbmuxd -f -v
autostart=true
autorestart=true
stderr_logfile=/altserver/logs/usbmuxd.err.log
stdout_logfile=/altserver/logs/usbmuxd.out.log
priority=10`

For the sake of completeness,  i added the parameters so that both usbmuxd and netmuxd can coexist with --disable-unix. Netmuxd require in addition the usbmuxd address socket to be set as an environment variable in dockerfile

> `ENV USBMUXD_SOCKET_ADDRESS=127.0.0.1:27015`


Just refreshed an altstore installation succesfully after these edits. Make sure to install sudo in the dockerfile

**Comment by dreth** [comment]
Hi! glad you were able to solve it, i'll fix the formatting on your comment so that anyone running into this issue in the future can try to use this fix. 

thank you!
